import { describe, expect, test } from "bun:test";

import { BlockType, parseLocalCommand, isLocalCommandMeta } from "@/supabase/types/message";

import { createPipeline } from "./pipeline";

// Raw JSONL local command format:
// <command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>

describe("parseLocalCommand", () => {
  test("parses local command with reversed tag order", () => {
    const content =
      "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>";
    const result = parseLocalCommand(content);
    expect(result).toEqual({ name: "clear", commandName: "/clear" });
  });

  test("parses /compact command", () => {
    const content =
      "<command-name>/compact</command-name>\n<command-message>compact</command-message>\n<command-args></command-args>";
    const result = parseLocalCommand(content);
    expect(result).toEqual({ name: "compact", commandName: "/compact" });
  });

  test("returns null for skill command format", () => {
    const content =
      "<command-message>claudebin:share</command-message>\n<command-name>/claudebin:share</command-name>";
    expect(parseLocalCommand(content)).toBeNull();
  });

  test("returns null for plain text", () => {
    expect(parseLocalCommand("hello world")).toBeNull();
  });
});

describe("isLocalCommandMeta", () => {
  test("detects local-command-caveat", () => {
    const content =
      "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>";
    expect(isLocalCommandMeta(content)).toBe(true);
  });

  test("detects local-command-stdout", () => {
    const content = "<local-command-stdout></local-command-stdout>";
    expect(isLocalCommandMeta(content)).toBe(true);
  });

  test("detects local-command-stdout with content", () => {
    const content =
      "<local-command-stdout>[2mCompacted (ctrl+o to see full summary)[22m</local-command-stdout>";
    expect(isLocalCommandMeta(content)).toBe(true);
  });

  test("returns false for plain text", () => {
    expect(isLocalCommandMeta("hello world")).toBe(false);
  });

  test("returns false for skill instructions", () => {
    expect(isLocalCommandMeta("<instructions>do something</instructions>")).toBe(false);
  });
});

// ABOUTME: Pipeline integration tests — verify local commands produce LOCAL_COMMAND blocks
// and that satellite messages (caveat, stdout) are filtered out
describe("pipeline local command integration", () => {
  const makeUserMsg = (content: string, isMeta = false) => ({
    type: "user" as const,
    uuid: crypto.randomUUID(),
    parentUuid: null,
    timestamp: "2025-01-01",
    isMeta,
    message: { content },
  });

  test("emits LOCAL_COMMAND block for /clear", () => {
    const pipeline = createPipeline();
    pipeline.ingest(
      makeUserMsg(
        "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>",
      ),
    );
    pipeline.flush();

    const messages = pipeline.getMessages();
    expect(messages).toHaveLength(1);
    expect(messages[0].content).toHaveLength(1);
    expect(messages[0].content[0].type).toBe(BlockType.LOCAL_COMMAND);
    expect((messages[0].content[0] as { commandName: string }).commandName).toBe("/clear");
  });

  test("filters out local-command-caveat meta message", () => {
    const pipeline = createPipeline();
    pipeline.ingest(
      makeUserMsg(
        "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
        true,
      ),
    );
    pipeline.ingest(
      makeUserMsg(
        "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>",
      ),
    );
    pipeline.flush();

    const messages = pipeline.getMessages();
    expect(messages).toHaveLength(1);
    expect(messages[0].content[0].type).toBe(BlockType.LOCAL_COMMAND);
  });

  test("filters out local-command-stdout message", () => {
    const pipeline = createPipeline();
    pipeline.ingest(
      makeUserMsg(
        "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>",
      ),
    );
    pipeline.ingest(makeUserMsg("<local-command-stdout></local-command-stdout>"));
    pipeline.flush();

    const messages = pipeline.getMessages();
    expect(messages).toHaveLength(1);
    expect(messages[0].content[0].type).toBe(BlockType.LOCAL_COMMAND);
  });

  test("attaches stdout output to LOCAL_COMMAND block", () => {
    const pipeline = createPipeline();
    pipeline.ingest(
      makeUserMsg(
        "<command-name>/compact</command-name>\n<command-message>compact</command-message>\n<command-args></command-args>",
      ),
    );
    pipeline.ingest(
      makeUserMsg(
        "<local-command-stdout>[2mCompacted (ctrl+o to see full summary)[22m</local-command-stdout>",
      ),
    );
    pipeline.flush();

    const messages = pipeline.getMessages();
    expect(messages).toHaveLength(1);
    const block = messages[0].content[0] as { type: string; output?: string };
    expect(block.type).toBe(BlockType.LOCAL_COMMAND);
    expect(block.output).toBe("[2mCompacted (ctrl+o to see full summary)[22m");
  });

  test("does not affect skill command parsing", () => {
    const pipeline = createPipeline();
    pipeline.ingest(
      makeUserMsg(
        "<command-message>claudebin:share</command-message>\n<command-name>/claudebin:share</command-name>",
      ),
    );
    pipeline.ingest(makeUserMsg("Use the MCP tool with these parameters...", true));
    pipeline.flush();

    const messages = pipeline.getMessages();
    expect(messages).toHaveLength(1);
    expect(messages[0].content[0].type).toBe(BlockType.SKILL);
  });
});
